/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AuthenticationRequest } from './models/authentication-request';
export type { AuthenticationResponse } from './models/authentication-response';
export type { Author } from './models/author';
export type { AuthorRequest } from './models/author-request';
export type { AuthorResponse } from './models/author-response';
export type { Book } from './models/book';
export type { BookRentingHistory } from './models/book-renting-history';
export type { BookRequest } from './models/book-request';
export type { BookResponse } from './models/book-response';
export type { BorrowedBookResponse } from './models/borrowed-book-response';
export type { GrantedAuthority } from './models/granted-authority';
export type { PageResponseAuthorResponse } from './models/page-response-author-response';
export type { PageResponseBookResponse } from './models/page-response-book-response';
export type { PageResponseBorrowedBookResponse } from './models/page-response-borrowed-book-response';
export type { RegistrationRequest } from './models/registration-request';
export type { Role } from './models/role';
export type { User } from './models/user';
