/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Author } from '../models/author';
export interface BookRequest {
  author: string;
  available?: boolean;
  bookCover?: string;
  categories: Array<'FICTION' | 'NON_FICTION' | 'SCIENCE_FICTION' | 'FANTASY' | 'MYSTERY' | 'THRILLER' | 'ROMANCE' | 'HORROR' | 'HISTORICAL_FICTION' | 'COMICS' | 'GRAPHIC_NOVEL' | 'BIOGRAPHY' | 'AUTOBIOGRAPHY' | 'SELF_HELP' | 'BUSINESS' | 'COOKING' | 'ART' | 'TRAVEL' | 'HISTORY' | 'SCIENCE' | 'POETRY' | 'DRAMA' | 'ACADEMIC' | 'REFERENCE' | 'CHILDREN' | 'YOUNG_ADULT' | 'MATURE_AUDIENCE'>;
  description: string;
  id?: number;
  isbn: string;
  title: string;
}
