/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Author } from '../models/author';
export interface BookResponse {
  author?: string;
  available?: boolean;
  categories?: Array<string | Category>;
  cover?: string;
  description?: string;
  id?: number;
  isbn?: string;
  title?: string;
}

export interface Category {
  id?: number;
  name?: string;
}
