/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Author } from '../models/author';
import { BookRentingHistory } from '../models/book-renting-history';
import { User } from '../models/user';
export interface Book {
  authors?: Array<Author>;
  available?: boolean;
  bookCover?: string;
  categories?: Array<'FICTION' | 'NON_FICTION' | 'SCIENCE_FICTION' | 'FANTASY' | 'MYSTERY' | 'THRILLER' | 'ROMANCE' | 'HORROR' | 'HISTORICAL_FICTION' | 'COMICS' | 'GRAPHIC_NOVEL' | 'BIOGRAPHY' | 'AUTOBIOGRAPHY' | 'SELF_HELP' | 'BUSINESS' | 'COOKING' | 'ART' | 'TRAVEL' | 'HISTORY' | 'SCIENCE' | 'POETRY' | 'DRAMA' | 'ACADEMIC' | 'REFERENCE' | 'CHILDREN' | 'YOUNG_ADULT' | 'MATURE_AUDIENCE'>;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  favouritedByUsers?: Array<User>;
  histories?: Array<BookRentingHistory>;
  id?: number;
  isbn?: string;
  lastModifiedBy?: string;
  lastModifiedDate?: string;
  title?: string;
}
