/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Author } from '../models/author';
export interface BorrowedBookResponse {
  author?: string;
  id?: number;
  isbn?: string;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
