spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_library
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: enkel
    password: enkel
    properties:
        mail:
            smtp:
              trust: "*" #not recommended for production
            auth: true
            starttls:
              enable: true
            connection-timeout: 5000
            timeout: 3000
            write-timeout: 5000
application:
  security:
    jwt:
      secret-key: f06f19371a1fa265f7f22743df61c765528f18885655171311bdd4e990ef6f39
      expiration: 86400000 # 1 day in milliseconds
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088