/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthorResponse } from '../../models/author-response';

export interface FindAuthorById$Params {
  'author-id': number;
}

export function findAuthorById(http: HttpClient, rootUrl: string, params: FindAuthorById$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthorResponse>> {
  const rb = new RequestBuilder(rootUrl, findAuthorById.PATH, 'get');
  if (params) {
    rb.path('author-id', params['author-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthorResponse>;
    })
  );
}

findAuthorById.PATH = '/authors/{author-id}';
